// Generate lib/api-schema.d.ts (TypeScript types for the platform API) from the backend's OpenAPI schema.
//
//   npm run gen:api                         dump the schema with Python (no server needed; temp data dirs)
//   OPENAPI_URL=http://127.0.0.1:8000/openapi.json npm run gen:api     read it from a running API instead
//   npm run gen:api -- --check              exit 1 if the committed file is out of date (for CI)
//
// Python is run from the repository root with DIP_DATA_DIR / DIP_LAKE_DIR pointed at empty temp dirs, so
// generating types never touches real data. Set PYTHON to choose the interpreter (default: python3).
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const out = path.join(root, "lib", "api-schema.d.ts");
const check = process.argv.includes("--check");

async function loadSchema() {
  if (process.env.OPENAPI_URL) {
    const r = await fetch(process.env.OPENAPI_URL);
    if (!r.ok) throw new Error(`GET ${process.env.OPENAPI_URL}: ${r.status}`);
    return r.json();
  }
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "dmis-openapi-"));
  try {
    const json = execFileSync(process.env.PYTHON ?? "python3",
      ["-c", "import json, sys; from dip.api.app import app; sys.stdout.write(json.dumps(app.openapi(), sort_keys=True))"],
      { cwd: path.resolve(root, ".."), env: { ...process.env, DIP_DATA_DIR: path.join(tmp, "platform"), DIP_LAKE_DIR: path.join(tmp, "lake") },
        stdio: ["ignore", "pipe", "inherit"], maxBuffer: 64 * 1024 * 1024 });
    return JSON.parse(json.toString("utf8"));
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
}

const schema = await loadSchema();
const header = `// GENERATED by scripts/gen-api.mjs from the platform API's OpenAPI schema -- do not edit by hand.
// Regenerate with \`npm run gen:api\` after changing FastAPI routes or Pydantic models.
// ${Object.keys(schema.paths ?? {}).length} paths. Most GET responses are untyped in the backend (no response_model), so
// their types here are \`unknown\`; request bodies (Pydantic models) are precise. See lib/api-typed.ts.\n\n`;
const body = header + astToString(await openapiTS(schema, { alphabetize: true, defaultNonNullable: false }));

if (check) {
  const cur = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : "";
  if (cur !== body) { console.error("lib/api-schema.d.ts is out of date: run `npm run gen:api`"); process.exit(1); }
  console.log("lib/api-schema.d.ts is up to date");
} else {
  fs.writeFileSync(out, body);
  console.log(`wrote ${path.relative(root, out)} (${Object.keys(schema.paths ?? {}).length} paths)`);
}
