"""live acquisition and sourcing runs; datasets.duplicate_reason (was missing from 0002)

Revision ID: 0003_acquisition
Revises: 0002_knowledge
Create Date: 2026-09-28 00:15:49.225981
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '0003_acquisition'
down_revision: Union[str, None] = '0002_knowledge'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisition_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('market_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('providers', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('ledger', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acquisition_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acquisition_runs_market_name'), ['market_name'], unique=False)

    op.create_table('sourcing_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('market_name', sa.String(length=255), nullable=True),
    sa.Column('concept', sa.JSON(), nullable=True),
    sa.Column('queries', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('ledger', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('by', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sourcing_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sourcing_runs_market_name'), ['market_name'], unique=False)

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duplicate_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('duplicate_reason')

    with op.batch_alter_table('sourcing_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sourcing_runs_market_name'))

    op.drop_table('sourcing_runs')
    with op.batch_alter_table('acquisition_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acquisition_runs_market_name'))

    op.drop_table('acquisition_runs')
    # ### end Alembic commands ###
