"""competitor watchlist

Revision ID: 0004_watchlist
Revises: 0003_acquisition
Create Date: 2026-09-28 01:20:25.304521
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '0004_watchlist'
down_revision: Union[str, None] = '0003_acquisition'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('asin', sa.String(length=32), nullable=False),
    sa.Column('market_name', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=500), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asin', 'market_name', name='uq_watch_asin_market')
    )
    with op.batch_alter_table('watch_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watch_items_asin'), ['asin'], unique=False)
        batch_op.create_index(batch_op.f('ix_watch_items_market_name'), ['market_name'], unique=False)

    op.create_table('watch_observations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('asin', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sales', sa.Float(), nullable=True),
    sa.Column('bsr', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watch_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watch_observations_asin'), ['asin'], unique=False)
        batch_op.create_index(batch_op.f('ix_watch_observations_observed_at'), ['observed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watch_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_watch_observations_asin'))

    op.drop_table('watch_observations')
    with op.batch_alter_table('watch_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watch_items_market_name'))
        batch_op.drop_index(batch_op.f('ix_watch_items_asin'))

    op.drop_table('watch_items')
    # ### end Alembic commands ###
