"""own sales

Revision ID: 0005_own_sales
Revises: 0004_watchlist
Create Date: 2026-09-28 07:13:09.969492
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '0005_own_sales'
down_revision: Union[str, None] = '0004_watchlist'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('own_sales',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('asin', sa.String(length=32), nullable=False),
    sa.Column('parent_asin', sa.String(length=32), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('period_start', sa.String(length=10), nullable=False),
    sa.Column('period_end', sa.String(length=10), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('orders', sa.Float(), nullable=True),
    sa.Column('sessions', sa.Float(), nullable=True),
    sa.Column('page_views', sa.Float(), nullable=True),
    sa.Column('conversion', sa.Float(), nullable=True),
    sa.Column('buy_box', sa.Float(), nullable=True),
    sa.Column('source_name', sa.String(length=500), nullable=True),
    sa.Column('imported_by', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asin', 'period_start', 'period_end', name='uq_own_sale_period')
    )
    with op.batch_alter_table('own_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_own_sales_asin'), ['asin'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('own_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_own_sales_asin'))

    op.drop_table('own_sales')
    # ### end Alembic commands ###
