"""Phase 2: how much do conclusions depend on the sales we cannot see?

SellerSprite exports carry monthly sales for only part of the products. Observed market size is a
lower bound. This analysis fills the missing sales with the 25th / 50th / 75th percentile of the
*observed* sales in the same segment (market-wide when the segment has none) and reports which
conclusions change: market size, segment ranking by revenue, top segment, segment leader brand,
market leader brand. The fills are scenarios for a sensitivity test -- they are never shown as data.
"""

from __future__ import annotations

import pandas as pd

from dip.storage import lake

SCENARIOS = {"observed": None, "p25": 0.25, "p50": 0.50, "p75": 0.75}


def _fill(products: pd.DataFrame, q: float | None) -> pd.DataFrame:
    p = products.copy()
    p["units"] = pd.to_numeric(p["monthly_sales"], errors="coerce")
    p["price_"] = pd.to_numeric(p["price"], errors="coerce")
    if q is not None:
        seg_q = p.groupby("segment_id")["units"].quantile(q)
        all_q = p["units"].quantile(q)
        fill = p["segment_id"].map(seg_q).fillna(all_q)
        p["units"] = p["units"].fillna(fill)
    p["rev"] = p["units"] * p["price_"]
    return p


def analyse(market: str) -> dict:
    products = lake.read_curated("products", market)
    segs = lake.read_curated("segments", market)
    if products.empty:
        return {"market": market, "status": "no_data"}
    labels = segs.set_index("segment_id")["segment_label"].to_dict() if len(segs) else {}
    known = pd.to_numeric(products["monthly_sales"], errors="coerce").notna()
    res = {}
    for name, q in SCENARIOS.items():
        p = _fill(products, q)
        seg_rev = p.groupby("segment_id")["rev"].sum(min_count=1).fillna(0).sort_values(ascending=False)
        leaders = (p.assign(brand=p["brand"].fillna("(unknown)")).groupby(["segment_id", "brand"])["rev"].sum()
                   .fillna(0).sort_values(ascending=False).reset_index().drop_duplicates("segment_id")
                   .set_index("segment_id")["brand"])
        brand_rev = p.assign(brand=p["brand"].fillna("(unknown)")).groupby("brand")["rev"].sum().sort_values(ascending=False)
        res[name] = {"market_revenue": float(p["rev"].sum()), "segment_rank": list(seg_rev.index),
                     "top_segment": seg_rev.index[0] if len(seg_rev) else None,
                     "segment_leaders": leaders.to_dict(), "market_leader": brand_rev.index[0] if len(brand_rev) else None,
                     "market_leader_share": float(brand_rev.iloc[0] / brand_rev.sum()) if brand_rev.sum() else None}
    base = res["observed"]
    flips = []
    for name in ("p25", "p50", "p75"):
        r = res[name]
        if r["top_segment"] != base["top_segment"]:
            flips.append(f"{name}: top segment becomes '{labels.get(r['top_segment'], r['top_segment'])}' "
                         f"(observed: '{labels.get(base['top_segment'], base['top_segment'])}')")
        if r["market_leader"] != base["market_leader"]:
            flips.append(f"{name}: market leader becomes {r['market_leader']} (observed: {base['market_leader']})")
        changed = [s for s, b_ in base["segment_leaders"].items() if r["segment_leaders"].get(s) != b_]
        if changed:
            flips.append(f"{name}: leader brand changes in {len(changed)} of {len(base['segment_leaders'])} segments "
                         f"({'; '.join(repr(labels.get(s, s)) for s in changed[:5])}{' …' if len(changed) > 5 else ''})")
    rank_corr = {}
    for name in ("p25", "p50", "p75"):
        a = pd.Series(range(len(base["segment_rank"])), index=base["segment_rank"])
        b_ = pd.Series(range(len(res[name]["segment_rank"])), index=res[name]["segment_rank"])
        both = a.index.intersection(b_.index)
        rank_corr[name] = float(a[both].corr(b_[both], method="spearman")) if len(both) >= 3 else None
    return {"market": market, "status": "ok", "products": int(len(products)), "sales_known": int(known.sum()),
            "sales_coverage": float(known.mean()),
            "market_revenue": {k: v["market_revenue"] for k, v in res.items()},
            "segment_rank_spearman_vs_observed": rank_corr,
            "top_segment": {k: labels.get(v["top_segment"], v["top_segment"]) for k, v in res.items()},
            "market_leader": {k: (v["market_leader"], v["market_leader_share"]) for k, v in res.items()},
            "flips": flips}


def to_markdown(results: list[dict]) -> str:
    L = ["# Sales-coverage sensitivity (Phase 2)", "",
         "Generated by `python scripts/pilot.py sensitivity`. Missing monthly sales are filled with the 25th / 50th / "
         "75th percentile of observed sales in the same segment (market-wide if none) **for this test only**; the "
         "platform never displays filled values. A conclusion that changes between scenarios is not robust to the "
         "unknown sales.", "",
         "Caveat: products whose sales SellerSprite shows are probably the stronger sellers, so percentiles of *observed* "
         "sales likely overstate the unknown ones -- read the fills as an upper range, and the observed figure as a floor.", "",
         "| Market | Sales known | Observed revenue/mo | If missing = p25 | p50 | p75 | Segment-rank Spearman (p25 / p50 / p75) |",
         "|---|---|---|---|---|---|---|"]
    for r in results:
        if r.get("status") != "ok":
            continue
        mr, sc = r["market_revenue"], r["segment_rank_spearman_vs_observed"]
        f = lambda v: "—" if v is None else f"{v:.2f}"  # noqa: E731
        L.append(f"| {r['market']} | {r['sales_known']}/{r['products']} ({r['sales_coverage']:.0%}) | ${mr['observed']:,.0f} | "
                 f"${mr['p25']:,.0f} | ${mr['p50']:,.0f} | ${mr['p75']:,.0f} | {f(sc['p25'])} / {f(sc['p50'])} / {f(sc['p75'])} |")
    L.append("")
    for r in results:
        if r.get("status") != "ok":
            continue
        L += [f"## {r['market']}", "",
              f"- Top segment — observed: **{r['top_segment']['observed']}**; p25: {r['top_segment']['p25']}; "
              f"p50: {r['top_segment']['p50']}; p75: {r['top_segment']['p75']}",
              "- Market leader — " + "; ".join(f"{k}: {v[0]} ({v[1]:.0%})" if v[1] is not None else f"{k}: {v[0]}"
                                              for k, v in r["market_leader"].items()),
              "- Conclusions that change:" if r["flips"] else "- No top-segment, market-leader or segment-leader conclusion changes."]
        L += [f"  - {x}" for x in r["flips"]]
        L.append("")
    return "\n".join(L)
